#!/usr/bin/env python
"""Emit `ziggurat_tables.js` -- the exact constants numpy's `standard_normal` samples against.

    conda run -n 4dre python web/tune/gen_ziggurat.py

These tables have to be numpy's OWN doubles, not a good reconstruction of them. The first
attempt rebuilt them from Marsaglia & Tsang's construction and got every entry right to
about 1e-10 -- which sounds close and is useless: `x = rabs * wi[idx]` then differs in the
low bits, so 99.6% of normal draws came out slightly different and the parity test failed on
every seed. There is no tolerance to hide in, because a random stream that is nearly right
is simply a different stream.

So this script does three things:

  1. Rebuilds the tables analytically (Marsaglia & Tsang at 256 levels). Not to ship -- to
     have a value to search FOR.
  2. Finds the real tables inside the installed numpy's compiled `_generator` module and
     extracts them. The search is anchored on the reconstruction rather than on fixed byte
     offsets, so it survives a rebuilt or differently-compiled numpy; it fails loudly rather
     than silently emitting the approximation.
  3. Writes them out as JS literals. Python's `repr` of a float round-trips exactly, so the
     numbers in the emitted file ARE these numbers.

`ki_double` is `uint64` in numpy's C and the other two are `double`, which is why the search
reads the same bytes two different ways. Every value fits in 2^53, so Float64Array holds
them exactly on the JS side and the `rabs < KI[idx]` comparison stays integer-exact.

The tables are mathematical constants from numpy (BSD-3-Clause). `tests/test_rng_parity.py`
is the proof that what lands in the JS reproduces numpy's stream bit for bit.
"""

import glob
import math
import os
import sys

import numpy as np

N = 256
# numpy's ZIGGURAT_NOR_R and the matching area constant for a 256-level normal ziggurat.
R = 3.6541528853610088
V = 0.00492867323399
# `rabs = (r >> 1) & 0x000fffffffffffff` in the sampler, so magnitudes run over 52 bits.
M1 = float(2 ** 52)
# The reconstruction lands within ~1e-9 of the real tables; anything looser would risk
# matching an unrelated run of doubles, anything tighter would miss the real one.
SEARCH_REL = 1e-5

HEADER = """// GENERATED by web/tune/gen_ziggurat.py -- do not edit by hand.
//
// The 256-level normal ziggurat, extracted from the compiled numpy that
// tests/test_rng_parity.py checks against. These are numpy's own doubles, not a
// reconstruction: rebuilding them from Marsaglia & Tsang's construction gets every entry
// right to ~1e-10, which changes the low bits of `rabs * WI[idx]` and so changes 99.6% of
// normal draws. See the generator's docstring.
//
// Mathematical constants from numpy (BSD-3-Clause).
"""


def reconstruct():
    """Marsaglia & Tsang's ziggurat setup at 256 levels -- the search key, not the output."""
    f = lambda x: math.exp(-0.5 * x * x)  # noqa: E731
    ki = [0.0] * N
    wi = [0.0] * N
    fi = [0.0] * N

    dn = R
    tn = dn
    q = V / f(dn)
    ki[0] = math.floor((dn / q) * M1)
    ki[1] = 0.0
    wi[0] = q / M1
    fi[0] = 1.0
    wi[N - 1] = dn / M1
    fi[N - 1] = f(dn)
    for i in range(N - 2, 0, -1):
        dn = math.sqrt(-2.0 * math.log(V / dn + f(dn)))
        ki[i + 1] = math.floor((dn / tn) * M1)
        tn = dn
        fi[i] = f(dn)
        wi[i] = dn / M1
    return ki, wi, fi


def find_table(words, target, label):
    """The one run of 256 values matching `target` to SEARCH_REL. Anchored on the entry with
    the largest magnitude, which is the most selective and cannot be a run of zeros."""
    approx = np.asarray(target, dtype=np.float64)
    vals = words.astype(np.float64)
    anchor_i = int(np.argmax(np.abs(approx)))
    anchor = approx[anchor_i]
    with np.errstate(all="ignore"):
        cand = np.flatnonzero(np.abs(vals - anchor) <= abs(anchor) * SEARCH_REL)
    hits = []
    for c in cand:
        s = int(c) - anchor_i
        if s < 0 or s + N > vals.size:
            continue
        seg = vals[s:s + N]
        with np.errstate(all="ignore"):
            rel = np.abs(seg - approx) / np.maximum(np.abs(approx), 1.0)
        if float(np.nanmax(rel)) < SEARCH_REL:
            hits.append(s)
    if len(hits) != 1:
        raise SystemExit(
            f"{label}: expected exactly one match in the numpy binary, found {len(hits)}. "
            "The table layout or the reconstruction has changed -- fix this rather than "
            "shipping the approximation, which is not bit-compatible.")
    return words[hits[0]:hits[0] + N], hits[0]


def emit(name, values, out, as_int=False):
    out.append(f"export const {name} = new Float64Array([")
    for i in range(0, len(values), 4):
        chunk = values[i:i + 4]
        text = ", ".join(str(int(v)) if as_int else repr(float(v)) for v in chunk)
        out.append("  " + text + ",")
    out.append("]);\n")


def main():
    ki_a, wi_a, fi_a = reconstruct()

    so = sorted(glob.glob(os.path.join(
        os.path.dirname(np.random.__file__), "_generator*.so")))
    if not so:
        raise SystemExit("no compiled numpy _generator module found to extract from")
    raw = open(so[0], "rb").read()
    usable = len(raw) // 8 * 8
    as_f8 = np.frombuffer(raw[:usable], dtype="<f8")
    as_u8 = np.frombuffer(raw[:usable], dtype="<u8")
    print(f"reading {os.path.basename(so[0])}  ({as_f8.size} machine words)")

    ki, ki_off = find_table(as_u8, ki_a, "ki_double")   # uint64 in numpy's C
    wi, wi_off = find_table(as_f8, wi_a, "wi_double")
    fi, fi_off = find_table(as_f8, fi_a, "fi_double")
    print(f"  ki_double @ word {ki_off}   wi_double @ {wi_off}   fi_double @ {fi_off}")
    for name, exact_t, approx_t in (("ki", ki, ki_a), ("wi", wi, wi_a), ("fi", fi, fi_a)):
        d = np.abs(exact_t.astype(np.float64) - np.asarray(approx_t, np.float64))
        rel = float((d / np.maximum(np.abs(np.asarray(approx_t, np.float64)), 1.0)).max())
        print(f"  {name}: reconstruction was off by up to {rel:.2e} -- extracted instead")

    if int(ki.max()) >= 2 ** 53:
        raise SystemExit("a ki_double entry exceeds 2^53 and would lose precision in JS")

    out = [HEADER.rstrip("\n"), ""]
    out.append(f"export const ZIGGURAT_NOR_R = {R!r};")
    out.append(f"export const ZIGGURAT_NOR_INV_R = {1.0 / R!r};")
    out.append("")
    emit("KI", ki, out, as_int=True)
    emit("WI", wi, out)
    emit("FI", fi, out)

    path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "ziggurat_tables.js")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {path}  ({N} levels)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
